### ISSUE TITLE
Clean up duplicated code in interfaces.ts

### ISSUE THREAD

**Issue by wpwood** [EOSIO/eosjs-signature-provider-interface#11]
Some code in https://github.com/EOSIO/eosjs-signature-provider-interface/blob/develop/src/interfaces.ts is duplicated from EOSJS because the interfaces are not exported. Once that issue is resolved, we can import them directly instead of defining them here.

**Comment by GreenBusDriver** [comment]
Looks like this work has been done.  I see nearly zero duplication now...
